services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_started
    links:
      - postgres
    env_file:
      - .env
    environment:
      - FLASK_DEBUG=${FLASK_DEBUG}
      - DYNAMODB_LOG_TABLE_NAME=${DYNAMODB_LOG_TABLE_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5000:5000
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    networks:
      - app-network

  postgres:
    image: postgres:15
    user: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/database/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - app-network

volumes:
  postgres-data:
networks:
  app-network:
    driver: bridge
